### ISSUE TITLE
White border around plain text messages when using Catppuccin Mocha theme

### ISSUE THREAD

**Issue by Occhioverde** [catppuccin/proton#1]
Good morning.
As the issue title says, today I noticed that plain text messages are shown with a thick white border around their body when using the Catppuccin Mocha theme:

![Mail view with Catppuccin Mocha enabled](https://user-images.githubusercontent.com/18429412/218318566-611b5e10-822b-4f52-bb4e-5f73c5c0db25.png)

For reference, here is the same message when Catppuccin Mocha is disabled:

![Mail view with Catppuccin Mocha disabled](https://user-images.githubusercontent.com/18429412/218318668-d3d36e25-a701-44b5-bb9f-e4a089e79498.png)

**Comment by soya-daizu** [comment]
Thanks for reporting the issue!

It seems like this is causing the issue.

https://github.com/catppuccin/proton/blob/7b1c25db266ecfe62c07df396032a76b25b8fee1/catppuccin.user.css#L252-L256

I first added this rule because the text appered in black color with black background when the Proton's theme is set to ones that have white backgrounds, but I think I'll just remove it and add an instruction to use a matching Proton theme to the catppuccin's flavor.

**Comment by soya-daizu** [comment]
Message content background should now conform to the base theme selected in Proton.
